### ISSUE TITLE
Run error in Arch Linux

### ISSUE THREAD

**Issue by zxp19821005** [pTinosq/clipio#12]
I've downloaded the source file,and add these in the `package.json` file:
```
  "build": {
    "appId": "com.ptinosq.clipio",
    "mac": {
      "icon": "src/icon.png"
    },
    "win": {
      "icon": "src/icon.png"
    },
    "linux": {
      "icon": "src/icon.png"
    }
```
When I run 
```
npm run app:dist
```
The program successfully generated the relevant files,such as `clipio-1.1.2-a.AppImage`,`clipio_1.1.2-a_amd64.snap`,files in `linux-unpacked`,and so on.
When I directlly run the  `clipio-1.1.2-a.AppImage` in the shell,I got an error:
```
$ ./dist/clipio-1.1.2-a.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'conf'
Require stack:
- /tmp/.mount_clipioDdCAD0/resources/app.asar/node_modules/electron-store/index.js
- /tmp/.mount_clipioDdCAD0/resources/app.asar/src/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_clipioDdCAD0/resources/app.asar/node_modules/electron-store/index.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
[97958:0613/133304.779462:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```
When I directlly run the  command `clipio` in `dist/linux-unpacked` directory in shell,I got the same error:
```
$ ./dist/linux-unpacked/clipio 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'conf'
Require stack:
- $HOME/.cache/paru/clone/clipio-1.1.2a/dist/linux-unpacked/resources/app.asar/node_modules/electron-store/index.js
- $HOME/.cache/paru/clone/clipio-1.1.2a/dist/linux-unpacked/resources/app.asar/src/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> ($HOME/.cache/paru/clone/clipio-1.1.2a/dist/linux-unpacked/resources/app.asar/node_modules/electron-store/index.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
[98176:0613/133326.276977:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
^C[98143:0613/133351.240623:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[98143:0613/133351.240731:ERROR:select_file_dialog_impl_portal.cc(243)] Failed to read portal version property
```
Will you please fix it?Thank you!

**Comment by pTinosq** [comment]
Hi, will look into this tomorrow. Thanks for the bug report 👍

**Comment by pTinosq** [comment]
@zxp19821005 Could you please run `node -v` to find your node version. I believe you might be using node version < 15.x

**Comment by zxp19821005** [comment]
```
$ node -v
v20.3.0
```

**Comment by pTinosq** [comment]
This might be a silly question but did you run `npm install`? If so, could you have a look at the node_modules directory and check to see if a folder called "conf" exists.

Here is a screenshot of what your root directory should look like:
![image](https://github.com/pTinosq/clipio/assets/46272051/c4676560-f53f-4d54-a403-62c20b175be2)

And here is a screenshot of the folder that should exist in your node_modules directory:
![image](https://github.com/pTinosq/clipio/assets/46272051/2e4fdb11-ec70-4b85-9d71-2e76c609d668)

Let me know what you find!

**Comment by zxp19821005** [comment]
Maybe I've forgot to run `rpm install`
### npm install
```
$ npm install
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.

added 659 packages in 18s

49 packages are looking for funding
  run `npm fund` for details
```
### npm run app:dist
```
$ npm run app:dist

> clipio@1.1.2a app:dist
> electron-builder

  • electron-builder  version=23.6.0 os=6.1.35-1-lts
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=17.4.11 appOutDir=dist/linux-unpacked
  • downloading     url=https://registry.npmmirror.com/-/binary/electron/17.4.11/electron-v17.4.11-linux-x64.zip size=82 MB parts=8
  • downloaded      url=https://registry.npmmirror.com/-/binary/electron/17.4.11/electron-v17.4.11-linux-x64.zip duration=5.032s
  • building        target=snap arch=x64 file=dist/clipio_1.1.2-a_amd64.snap
  • building        target=AppImage arch=x64 file=dist/clipio-1.1.2-a.AppImage
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
```
### ./dist/linux-unpacked/clipio
```
$ ./dist/linux-unpacked/clipio 
[306427:0625/175717.855443:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[306391:0625/175717.872087:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
```
### ./dist/clipio-1.1.2-a.AppImage
```
$ ./dist/clipio-1.1.2-a.AppImage 
[306748:0625/175811.672091:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[306710:0625/175811.829976:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[306710:0625/175836.519662:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[306710:0625/175836.519744:ERROR:select_file_dialog_impl_portal.cc(243)] Failed to read portal version property
```
